# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_api', '0004_auto_20191112_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTemplates',
            fields=[
                ('id', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('application_interface', models.CharField(max_length=2048)),
                ('gatewayId', models.CharField(max_length=2048)),
            ],
        ),
    ]
