# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_api', '0005_parsingtemplates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsingTemplates',
        ),
    ]
