- name: "Installing Consul"
  yum:
     name: haproxy
     state: installed	

- name: Download Consul
  sudo: true
  get_url:
    url:  https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
    dest: /usr/local/bin

- name: Install Conul
  sudo: true
  shell: unzip consul_1.0.0_linux_amd64.zip && rm -rf consul_1.0.0_linux_amd64.zip && useradd -m consul && usermod -aG sudo consul 
  args: 
    chdir: /usr/local/bin

- name: Doenload Consul Configuration
  become: yes
  become_user: consul
  shell: curl -o consul_client.py https://raw.githubusercontent.com/jerrin92/airavata-django-portal/load-balancing/LoadBalancer/Consul/client/consul_client.py && /usr/bin/python consul_client.py && consul agent -enable-script-checks -config-dir /etc/consul.d/client  

